### ISSUE TITLE
Crawler each() method is too rigid.

### ISSUE THREAD

**Issue by iifeoluwa** [unicodeveloper/mvrd#3]
I am working on making the vehicle data easily available as key value pairs but I have hit a brick wall with DomCrawler's `each()` method in the Crawler class. 

I discovered that `each()` and many other functions returns arrays only and this is a pain to work with as seen in the test array I sent below.

![crawl](https://cloud.githubusercontent.com/assets/15154504/21524234/db4c672e-cd14-11e6-866c-bc128264437e.PNG)

I've attached another image in case it helps.
![crawler](https://cloud.githubusercontent.com/assets/15154504/21524246/04eae6a0-cd15-11e6-8a1f-ac58cdbb888c.PNG)

How do I override this please and only return my own array?
Thanks.

**Comment by unicodeveloper** [comment]
I think you can get the array, explode it and convert them into JSON values to be returned as key value pairs

**Comment by iifeoluwa** [comment]
Thanks a lot man. Problem is, I wasn't even thinking. My bad.
